### ISSUE TITLE
'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by amatteini** [bugsink/bugsink#15]
I run the docker setup. When I try to open some issues details, I get a 500 error.

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
>     response = get_response(request)
>                ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/bugsink/decorators.py", line 110, in wrapper
>     return function(request, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/bugsink/decorators.py", line 45, in wrapper
>     return function(request, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/issues/views.py", line 333, in issue_event_stacktrace
>     return render(request, "issues/stacktrace.html", {
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/shortcuts.py", line 24, in render
>     content = loader.render_to_string(template_name, context, request, using=using)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
>     return template.render(context, request)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
>     return self.template.render(context)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 175, in render
>     return self._render(context)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
>     return self.nodelist.render(context)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
>     return SafeString("".join([node.render_annotated(context) for node in self]))
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
>     return self.render(context)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 157, in render
>     return compiled_parent._render(context)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
>     return self.nodelist.render(context)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
>     return SafeString("".join([node.render_annotated(context) for node in self]))
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
>     return self.render(context)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 157, in render
>     return compiled_parent._render(context)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
>     return self.nodelist.render(context)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
>     return SafeString("".join([node.render_annotated(context) for node in self]))
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
>     return self.render(context)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 63, in render
>     result = block.nodelist.render(context)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
>     return SafeString("".join([node.render_annotated(context) for node in self]))
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
>     return self.render(context)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 63, in render
>     result = block.nodelist.render(context)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
>     return SafeString("".join([node.render_annotated(context) for node in self]))
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
>     return self.render(context)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 238, in render
>     nodelist.append(node.render_annotated(context))
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
>     return self.render(context)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 238, in render
>     nodelist.append(node.render_annotated(context))
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
>     return self.render(context)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 539, in render
>     values = {key: val.resolve(context) for key, val in self.extra_context.items()}
>                    ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 742, in resolve
>     new_obj = func(obj, *arg_vals)
>               ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/theme/templatetags/issues.py", line 93, in pygmentize
>     lines = _pygmentize_lines(code_as_list, filename=filename, platform=platform)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/theme/templatetags/issues.py", line 65, in _pygmentize_lines
>     lines = [" " if line == "" else line for line in [l.replace("\n", "") for l in lines]]
>                                                       ^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'replace'
> 11.22.33.44 - - [06/Dec/2024:14:44:39 +0000] "GET /issues/issue/123-456/event/last/ HTTP/1.0" 500
> 
>

**Comment by vanschelven** [comment]
I'll have a fix for this soon. I'd be curious which SDK sends events like this and if you are able to send a (redacted) version of the event though, would be helpful (at the least to satisfy my curiosity).

**Comment by amatteini** [comment]
Thanks!

Using sentry-ruby (5.21.0)
